const serie1 = 
    [{name : "13 Reasons Why",
    id : "13RW",
    trailer : "https://www.youtube.com/embed/0XuOkYlUWIs",
    description :"Drama, Love, +18",
    rating : "5",
    posterURL : "https://www.presse-citron.net/app/uploads/2019/08/nouvelle-bande-annonce-13-reason-why-saison-3.jpg"},{name:"Squid Game",
    id : "squid-game",
    trailer : "https://www.youtube.com/embed/oqxAJKy0ii4",
    description :"Drama, Risk, +16",
    rating : "3",
    posterURL : "https://phantom-marca.unidadeditorial.es/8256e68fdfac5b6a6c792af7308d27e8/crop/0x0/1597x899/resize/1320/f/jpg/assets/multimedia/imagenes/2021/10/01/16330974723192.png"},{name:"La Casa De Papel",
    id : "casa-de-papel",
    trailer : "https://www.youtube.com/embed/htqXL94Rza4",
    description :"Kill, +20",
    rating : "4",
    posterURL : "https://occ-0-1723-1722.1.nflxso.net/dnm/api/v6/X194eJsgWBDE2aQbaNdmCXGUP-Y/AAAABXyRbOhbY4IW7PPIkjjYINiqBXRg5X3u3DDst43Z3lK_TtDzypvMardjfWq0jk_V7ra2s-rCye12rNmc7fQPwIbTi_UMmDXwk8VBkkZqGXJNNPphcGKxKCAidNqNsQ.jpg?r=19a"}]

  const serie2 = 
    [{name : "Baby Boss",
    id : "baby-boss",
    trailer : "https://www.youtube.com/embed/k397HRbTtWI",
    description :"Comic, +3",
    rating : "4",
    posterURL : "https://flxt.tmsimg.com/assets/p15289801_b_h8_aq.jpg"},{name:"Pokemon",
    id : "pokemon",
    trailer : "https://www.youtube.com/embed/iF4o64-LO0Q",
    description :"Risk, +6",
    rating : "2",
    posterURL : "https://assets.pokemon.com/assets/cms2-en-uk/img/watch-pokemon-tv/_tiles/season23/announce/season23-announce-169-en.jpg"},{name:"Peppa Pig",
    id : "peppa-pig",
    trailer : "https://www.youtube.com/embed/Oozdpz12Ejo",
    description :"kids, +3",
    rating : "5",
    posterURL : "https://images.radio-canada.ca/v1/ici-tou-tv/emissions/16x9/apple_peppapig.jpg"},{name : "Sweet Tooth",
    id : "sweet-tooth",
    trailer : "https://www.youtube.com/embed/9zG9RuJb3QU",
    description :"Drama, +8",
    rating : "5",
    posterURL : "https://i.ytimg.com/vi/8LsairirWGQ/maxresdefault.jpg"},{name:"Next Gen",
    id : "next-gen",
    trailer : "https://www.youtube.com/embed/uf3ALGKgpGU",
    description :"Robot, +6",
    rating : "1",
    posterURL : "https://gracefulcoffee.files.wordpress.com/2018/10/bb7056b682f00c4144791aec3ee73b66b6cae3a6.jpg"},]

export {serie1,serie2};

// {name:"You",
//     description :"Kill, Drama, +18",
//     rating : "96 %",
//     posterURL : "https://www.culturefemme.com/wp-content/uploads/2021/10/you.png.jpeg"}